os:
  - linux
services:
  - docker
env:
  global:
    - JHIPSTER_CACHE_REPO=https://github.com/jhipster/jhipster-travis-cache.git
    - JHIPSTER_CACHE_BRANCH=160516-springboot-135
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
    - JHIPSTER_DOCKER=$JHIPSTER_TRAVIS/docker
install:
  - $JHIPSTER_INSTALL/01-install-docker-compose.sh
  - $JHIPSTER_INSTALL/04-cache.sh
  - docker version
  - docker-compose version
  - docker build -t jhipster-tester docker/Dockerfile docker/
script:
  - $JHIPSTER_TRAVIS/01-run-docker-tests.sh
  - $JHIPSTER_SCRIPTS/07-checkDocker.sh
